services:
  - type: web
    name: mini-lugat
    env: node
    buildCommand: bash build.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
